language: node_js
node_js:
- '4'
env:
- CXX=g++-4.8
addons:
  ssh_known_hosts: 128.199.215.215
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_280961f95bfb_key -iv $encrypted_280961f95bfb_iv
  -in deploy-key.enc -out deploy-key -d
- bash _bash_scripts/install.sh
after_success:
- bash _bash_scripts/deploy.sh
